name: APK Auto Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Clone Versions Branch
        run: |
          git clone --single-branch --branch app-version-apps https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git apk-temp || (
            mkdir apk-temp && cd apk-temp && git init && git checkout -b app-version-apps
          )

      - name: Save APK
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d_%I-%M-%p")
          mkdir -p apk-temp/versions
          cp build/app/outputs/flutter-apk/app-release.apk apk-temp/versions/app-${TIMESTAMP}.apk

      - name: Commit & Push APK
        run: |
          cd apk-temp
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add versions/
          git commit -m "Add APK: app-$(date +'%Y-%m-%d %I:%M %p').apk" || echo "Nothing to commit"
          git push origin app-version-apps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
