name: Unsigned Android Build Apk

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Setup Git and Clone or Init Branch
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git apk-temp
          cd apk-temp
          if git ls-remote --exit-code --heads origin apk-unsigned; then
            git checkout apk-unsigned
          else
            git checkout --orphan apk-unsigned
            git rm -rf . || true
          fi

      - name: Store Apk
        run: |
          cp build/app/outputs/flutter-apk/app-release.apk apk-temp/unsigned.apk

      - name: Commit & Push APK
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd apk-temp
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add unsigned.apk
          git commit -m "Update unsigned APK" || echo "Nothing to commit"
          git push -u origin apk-unsigned
